name: Azure Static Web Apps Main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_SKY_0AA0A9E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "/api/function/" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      - name: Upload to blob
        id: upload
        uses: azure/CLI@v1
        env:
          STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
          STORAGE_CONTAINER: cdn
          STORAGE_KEY: ${{ secrets.STORAGE_KEY }}
        with:
          inlineScript: |
            mkdir /tmp/blobSource
            cp -R ./* /tmp/blobSource/
            cd /tmp/blobSource
            echo "Uploading to blob"
            az storage blob upload-batch -s . -d "${STORAGE_CONTAINER}" --account-name "${STORAGE_ACCOUNT}" --account-key "${STORAGE_KEY}" --overwrite